# Generated by Django 5.2.11 on 2026-04-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField()),
                ('total_at_risk', models.IntegerField()),
                ('avg_engagement', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_student', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('code_module', models.CharField(max_length=10)),
                ('code_presentation', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=2)),
                ('region', models.CharField(max_length=100)),
                ('highest_education', models.CharField(max_length=100)),
                ('imd_band', models.CharField(blank=True, max_length=10, null=True)),
                ('age_band', models.CharField(max_length=10)),
                ('num_of_prev_attempts', models.IntegerField(default=0)),
                ('studied_credits', models.IntegerField(default=0)),
                ('disability', models.CharField(max_length=2)),
                ('avg_first_two_score', models.FloatField(default=0.0)),
                ('total_clicks', models.FloatField(default=0.0)),
                ('max_inactivity_gap', models.IntegerField(default=0)),
                ('perf_at_risk', models.BooleanField(default=False)),
                ('click_at_risk', models.BooleanField(default=False)),
                ('inactivity_at_risk', models.BooleanField(default=False)),
                ('is_at_risk', models.BooleanField(default=False)),
                ('risk_probability', models.FloatField(default=0.0)),
            ],
        ),
    ]
